spring:
  application:
    name: library_api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/library
    username: postgres
    password: postgres
  jpa:
    hibernate:
#      ddl-auto: update
      ddl-auto: none
    show-sql: true

server:
  port: 3000