CREATE TABLE author (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_user UUID NOT NULL
);

CREATE TABLE book (
    id UUID NOT NULL PRIMARY KEY,
    isbn VARCHAR(20) NOT NULL,
    title VARCHAR(150) NOT NULL,
    publication_date DATE NOT NULL,
    genre VARCHAR(30) NOT NULL,
    price DECIMAL(10, 2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_user UUID,
    id_author UUID NOT NULL REFERENCES author(id),
    CONSTRAINT chk_genre CHECK ( genre in ('FICTION', 'FANTASY', 'ROMANCE', 'BIOGRAPHY', 'SCIENCE') )
);

CREATE TABLE users (
    id UUID NOT NULL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    roles VARCHAR[](10),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
